config/routes.rb
Rails.application.routes.draw do
  resources :comments do
    collection do
      get :toggle_please_check
    end
  end
  resources :attestations
  resources :users
  resources :extracts do
    member do
      get :check_upload
    end
  end

  get 'text_dashboard', to: 'dashboards#text_module'
  resources :dashboards do
    collection do
      post :upload_and_parse
    end
  end


  root to: 'dashboards#text_module'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attestation.rb
class Attestation < ApplicationRecord
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User'

  belongs_to :extract
  has_many :comments, as: :commentable

  validates :orthography, presence: true
end

app/controllers/attestations_controller.rb
class AttestationsController < ApplicationController
  before_action :set_attestation, only: [:edit, :update, :destroy]

  # GET /attestations
  # GET /attestations.json
  def index
    @attestations = Attestation.all
  end

  # GET /attestations/new
  def new
    new_attestation_for_extract
  end

  # GET /attestations/1/edit
  def edit
  end

  # POST /attestations
  def create
    extract_coptic = params[:attestation].delete(:extract_coptic)
    extract_translation = params[:attestation].delete(:extract_translation)

    current_user = User.find_by_code('Admin')
    @attestation = Attestation.new(attestation_params.merge(created_by: current_user, updated_by: current_user))

    respond_to do |format|
      if @attestation.save
        while extract_coptic.include? '#' do
          extract_coptic.sub! '#', "<attestation id='#{@attestation.id}'>"
          extract_coptic.sub! '#', '</attestation>'
        end
        while extract_translation.include? '#' do
          extract_translation.sub! '#', '<attestation>'
          extract_translation.sub! '#', '</attestation>'
        end
        @attestation.extract.update(coptic: extract_coptic, translation: extract_translation)
        format.html { redirect_to extract_path(@attestation.extract), flash: {success: 'Attestation was successfully created.'} }
      else
        flash.now[:error] = "The following errors occurred. Please fix them and try again:\n #{@attestation.errors.full_messages.join('. ')}."
        format.html { render :new  }
      end
    end
  end

  # PATCH/PUT /attestations/1
  def update
    respond_to do |format|
      if @attestation.update(attestation_params)
        format.html { redirect_to extract_path(@attestation.extract), flash: {success: 'Attestation was successfully updated.'} }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /attestations/1
  def destroy
    extract = @attestation.extract
    @attestation.destroy
    delete_attestation_from_coptic @attestation, extract
    respond_to do |format|
      format.html { redirect_to extract_url(extract), flash: {success: 'Attestation was successfully destroyed.'} }
    end
  end

  private

  def new_attestation_for_extract
    extract_id = params.fetch(:extract_id, nil)
    @attestation = Attestation.new(extract_id: extract_id)
  end

  def delete_attestation_from_coptic(attestation, extract)
    coptic = extract.coptic
    parts = attestation.orthography.split(' ... ')
    parts.each do |p|
      attestation_node = "<attestation id='#{attestation.id}'>#{p}</attestation>"
      coptic.sub! attestation_node, p
    end
    extract.update(coptic: coptic)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_attestation
    @attestation = Attestation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attestation_params
    params.require(:attestation).permit(:orthography, :encoding, :extract_id, :created_by_id, :updated_by_id)
  end
end

app/views/attestations/_form.html.haml
= bootstrap_form_with model: @attestation, local: true, class: 'needs-validation novalidate' do |f|

  - unless @attestation.id
    = f.hidden_field :extract_id, value: @attestation.extract_id
    - extract_with_line_breaks = @attestation.extract.add_line_breaks

    .row.mb-3
      .col-6
        .form-group
          = f.text_area :extract_coptic, value: extract_with_line_breaks.coptic, rows: '10', class: 'form-control antinoou'
          = f.hidden_field :extract_coptic_original, value: extract_with_line_breaks.coptic
      .col-6
        .form-group
          = f.text_area :extract_translation, value: extract_with_line_breaks.translation, rows: '10', class: 'form-control translation-field'
          = f.hidden_field :extract_translation_original, value: extract_with_line_breaks.translation
    .row.mb-5
      %small.col-12
        Zeilenumbrüche dienen nur der Übersichtlichkeit und werden nicht gespeichert.

    .row
      .col-3.text-center
        = link_to 'Extract Orthography', '#', id:'extract_orthography', 'data-turbolinks': 'false', class: 'btn-resource-action mr-5'
      .col-3.text-center
        = link_to 'Reset Changes', '#', id: 'clear_orthography', 'data-turbolinks': 'false', class: 'btn-resource-action'
      .col-6
        #extract-errors.text-danger
          = fa_icon('exclamation-triangle')
          %span#extract-error-message

  .row
    .form-group.col-6
      = f.text_field :orthography, readonly: true, class: 'form-control antinoou'

    .form-group.col-6
      = f.text_field :encoding, class: 'form-control'

  .row
    .col-12
      .actions
        = f.submit

app/views/attestations/_preview.html.haml
.row
  .col-2
    = attestation.id
    = user_info_tooltip attestation
  .col-4.antinoou
    = attestation.orthography
  .col-4
    = attestation.encoding
  .col-2
    .row
      .col-6
        = link_to fa_icon('times'), attestation, method: :delete, data: { confirm: 'Do you want to delete this attestation permanently?' }, class: 'btn btn-block btn-resource-action'
      .col-6
        = link_to fa_icon('edit'), edit_attestation_path(attestation), class: 'btn btn-block btn-resource-action'

app/views/attestations/edit.html.haml
%nav{'aria-label': 'breadcrumb', role: 'navigation'}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to 'Text Module Dashboard', text_dashboard_url
    %li.breadcrumb-item
      = link_to 'Extracts', extracts_url
    %li.breadcrumb-item
      = link_to @attestation.extract.id, extract_url(@attestation.extract)
    %li.breadcrumb-item.active{'aria-current': 'page'}
      Attestation
      = @attestation.id


.container
  .row
    .col-12
      = render 'form', attestation: @attestation

app/views/attestations/index.html.haml
%nav{'aria-label': 'breadcrumb', role: 'navigation'}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to 'Text Module Dashboard', text_dashboard_url
    %li.breadcrumb-item.active{'aria-current': 'page'}
      Attestations

.container
  .row
    .col-12
      %h1.mb-4.border-bottom
        Attestations

  %table.table
    %thead.thead-light
      %tr
        %th Orthography
        %th Encoding
        %th Extract
    %tbody
      - @attestations.each do |attestation|
        %tr
          %td.antinoou= attestation.orthography
          %td= attestation.encoding
          %td= link_to 'Go to Extract', attestation.extract

app/views/attestations/new.html.haml
%nav{'aria-label': 'breadcrumb', role: 'navigation'}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to 'Text Module Dashboard', text_dashboard_url
    %li.breadcrumb-item
      = link_to 'Extracts', extracts_url
    %li.breadcrumb-item
      = link_to @attestation.extract_id, extract_url(@attestation.extract_id)
    %li.breadcrumb-item.active{'aria-current': 'page'}
      Attestation
      = @attestation.id


.container
  .row
    .col-12
      = render 'form', attestation: @attestation