config/routes.rb
Rails.application.routes.draw do
  resources :comments do
    collection do
      get :toggle_please_check
    end
  end
  resources :attestations
  resources :users
  resources :extracts do
    member do
      get :check_upload
    end
  end

  get 'text_dashboard', to: 'dashboards#text_module'
  resources :dashboards do
    collection do
      post :upload_and_parse
    end
  end


  root to: 'dashboards#text_module'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/extract.rb
class Extract < ApplicationRecord
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User'

  has_many :attestations
  has_many :comments, as: :commentable

  validates :coptic, presence: true
  validates :edition_position, presence: true
  validate :coptic_is_tagged_correctly, on: [:create, :update]

  before_save :remove_line_breaks

  def add_line_breaks
    substitutions = [['<attestation', "\n<attestation"],
                     ['</attestation>', "</attestation>\n"]]
    substitutions.each do |s|
      coptic.gsub! s.first, s.second
      translation.gsub! s.first, s.second
    end
    self
  end

  private

  def remove_line_breaks
    coptic.delete! "\r\n"
    translation&.delete! "\r\n"
  end

  def coptic_is_tagged_correctly
    all_attestations_present = attestations.count > 0 ? attestations.map {|a| coptic.include? "<attestation id='#{a.id}'>"}.reduce(:&) : true
    coptic_as_xml = '<root>' + coptic + '</root>' if coptic.present?
    well_formed = Nokogiri::XML(coptic_as_xml).errors.none?

    unless all_attestations_present && well_formed
      errors.add :base, 'Unexpected tagging in Coptic field.'
    end
  end
end

app/controllers/extracts_controller.rb
class ExtractsController < ApplicationController
  before_action :set_extract, only: [:show, :edit, :update, :destroy]

  # GET /extracts
  # GET /extracts.json
  def index
    @extracts = Extract.all.order(checked_upload: :desc, id: :asc)
  end

  # GET /extracts/1
  # GET /extracts/1.json
  def show
  end

  # GET /extracts/new
  def new
    @extract = Extract.new
  end

  # GET /extracts/1/edit
  def edit
    @extract.add_line_breaks
  end

  # POST /extracts
  def create
    creator = User.find_by_code('Admin')
    @extract = Extract.new(extract_params.merge({created_by: creator, updated_by: creator}))

    respond_to do |format|
      if @extract.save
        format.html { redirect_to @extract, flash: {success: 'Extract was successfully created.'} }
      else
        flash.now[:error] = "The following errors occured. Please fix them and try again: #{@extract.errors.full_messages.join('. ')}"
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /extracts/1
  def update
    attestations = @extract.attestations
    respond_to do |format|
      if @extract.update(extract_params)
        attestations.each do |attestation|
          parts = Nokogiri::HTML(@extract.coptic).xpath("//attestation[@id='#{attestation.id}']/text()").map(&:content)
          attestation.update(orthography: parts.join(' ... '))
        end
        format.html { redirect_to @extract, flash: {success: 'Extract was successfully updated.'} }
      else
        flash.now[:error] = "The following errors occured. Please fix them and try again: #{@extract.errors.full_messages.join('. ')}"
        format.html { render :edit }
      end
    end
  end

  # DELETE /extracts/1
  def destroy
    @extract.destroy
    respond_to do |format|
      format.html { redirect_to extracts_url, flash: {sucess: 'Extract was successfully destroyed.'} }
    end
  end

  def check_upload
    set_extract
    @extract.update(checked_upload: true)
    redirect_back fallback_location: root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_extract
    @extract = Extract.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def extract_params
    params.require(:extract).permit(:coptic, :translation,
                                    :manuscript_position, :text_position, :edition_position,
                                    :unchecked_quote, :quote_origin, :quote_type, :checked_upload)
  end
end

app/helpers/extracts_helper.rb
module ExtractsHelper
  def highlight_attestations(text)
    return text if text.nil? || text.index('^').nil?

    opening_tag = '<span class="attestation-tag">'
    closing_tag = '</span>'
    text_mod = ''
    is_open = false
    text.each_char do |char|
      if char.eql?('^') && is_open
        text_mod += char + closing_tag
        is_open = false
      elsif char.eql?('^') && !is_open
        text_mod += opening_tag + char
        is_open = true
      else
        text_mod += char
      end
    end
    text_mod
  end

  def wrong_tag_count_note(extract)
    odd_tag_number_in_coptic = extract.coptic.count('^').odd?
    odd_tag_number_in_transl = extract.translation.try { count('^').odd? }

    return unless odd_tag_number_in_coptic || odd_tag_number_in_transl

    where = []
    where << 'Coptic Text' if odd_tag_number_in_coptic
    where << 'Translation' if odd_tag_number_in_transl

    haml_tag :div, class: 'text-danger' do
      haml_concat fa_icon('exclamation-triangle')
      haml_concat "Odd Number of Tags in #{where.join(' and ')}"
    end
  end

  def unchecked_upload_note(extract, options={})
    note_class = options.fetch(:class, '')
    if extract.checked_upload
      haml_tag :div, class: 'text-success ' + note_class do
        haml_concat fa_icon('check')
        haml_concat 'Checked Upload'
      end
    else
      haml_tag :div, class: 'text-danger ' + note_class do
        haml_concat fa_icon('exclamation-triangle')
        haml_concat 'Unchecked Upload'
      end
    end
  end

end

app/views/extracts/_form.html.haml
= bootstrap_form_with model: extract, local: true do |form|
  .row
    .col-6
      .form-group
        = form.text_area :coptic, class: 'form-control antinoou', rows: '10'

    .col-6
      .form-group
        = form.text_area :translation, class: 'form-control translation-field', rows: '10'
  .row.mb-5
    %small.col-12
      Zeilenumbrüche dienen nur der Übersichtlichkeit und werden nicht gespeichert.
      Neue Attestationen werden
      = link_to 'hier', new_attestation_path(params: {extract_id: extract.id})
      hinzugefügt werden.
      %br
      Bei Klick in ein Tag-Element wird das gesamte Element markiert.
  .row.mb-3
    .col-12
      .row
        .col-4
          .form-group
            = form.text_field :manuscript_position, class: 'form-control'
        .col-4
          .form-group
            = form.text_field :text_position, class: 'form-control'
        .col-4
          .form-group
            = form.text_field :edition_position, class: 'form-control'
  .row.mb-3
    .col-4
      .form-group
        = form.text_field :quote_origin, class: 'form-control'
    .col-4
      .form-group
        = form.text_field :quote_type, class: 'form-control'
  .row.mb-3
    .col-2
      .form-group
        = form.check_box :unchecked_quote
    .col-2
      .form-group
        = form.check_box :checked_upload, checked: true
  .actions
    = form.submit

app/views/extracts/_preview.html.haml
.row
  .col-2
    = extract.id
    = user_info_tooltip extract
  .col-2
    - if extract.edition_position.present?
      Edition:
      = extract.edition_position
  .col-2
    - if extract.manuscript_position.present?
      Manuscript:
      = extract.manuscript_position
  .col-2
    - if extract.text_position.present?
      Text:
      = extract.text_position
  .col-4
    - unchecked_upload_note extract, class: 'float-right'
.row.mt-3
  .col-6.antinoou
    != highlight_attestations extract.coptic
  .col-6.increased-line-height
    != highlight_attestations extract.translation

.row
  .col-10
    - wrong_tag_count_note extract
  .col-1
    = link_to "#{fa_icon('eye')} View".html_safe, extract_path(extract), class: 'btn btn-block btn-resource-action'
  .col-1
    = link_to "#{fa_icon('edit')} Edit".html_safe, edit_extract_path(extract), class: 'btn btn-block btn-resource-action'

app/views/extracts/edit.html.haml
%nav{'aria-label': 'breadcrumb', role: 'navigation'}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to 'Text Module Dashboard', text_dashboard_url
    %li.breadcrumb-item
      = link_to 'Extracts', extracts_url
    %li.breadcrumb-item.active{'aria-current': 'page'}
      = link_to @extract.id, extract_url(@extract)

.container
  .row.mb-3
    .col-12
      = render 'form', extract: @extract

app/views/extracts/index.html.haml
%nav{'aria-label': 'breadcrumb', role: 'navigation'}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to 'Text Module Dashboard', text_dashboard_url
    %li.breadcrumb-item.active{'aria-current': 'page'}
      Extracts

.container
  .row
    .col-12
      %h1.mb-4.border-bottom
        Extracts

  .row.mb-5
    .col-12
      = link_to "#{fa_icon('plus')} New Extract".html_safe, new_extract_path, class: 'btn btn-resource-action'
  .row
    .col-12.card
      %ul.preview-list
        - @extracts.each do |extract|
          %li
            .row
              .col-12
                = render partial: 'extracts/preview', locals: {extract: extract}

app/views/extracts/new.html.haml
%nav{'aria-label': 'breadcrumb', role: 'navigation'}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to 'Text Module Dashboard', text_dashboard_url
    %li.breadcrumb-item.active{'aria-current': 'page'}
      = link_to 'Extracts', extracts_url

.container
  .row
    .col-12
      = render 'form', extract: @extract

app/views/extracts/show.html.haml
%nav{'aria-label': 'breadcrumb', role: 'navigation'}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to 'Text Module Dashboard', text_dashboard_url
    %li.breadcrumb-item
      = link_to 'Extracts', extracts_url
    %li.breadcrumb-item.active{'aria-current': 'page'}
      = @extract.id

.container
  %h3.mt-3.mb-3
    Extract

  .card-deck
    .card
      .card-body
        .card-text.antinoou
          != @extract.coptic
      .card-footer
        %hr
        .row
          .col-3.offset-1
            = comment_button '#copticComment'
          .col-3
            = toggle_please_check_button @extract, 'coptic'
    .card
      .card-body
        .card-text.translation-field
          != @extract.translation
      .card-footer
        %hr
        .row
          .col-3.offset-1
            = comment_button '#translationComment'
          .col-3
            = toggle_please_check_button @extract, 'translation'
  .card-deck.mb-3
    .card.card-comment
      .card-body
        .card-text
          = render partial: 'comments/show_comments', locals: {commented_entry: @extract, field: 'coptic'}
          = render partial: 'comments/add_comment', locals: {target_id: 'copticComment', field: 'coptic', commentable: @extract, comment: Comment.new}
    .card.card-comment
      .card-body
        .card-text
          = render partial: 'comments/show_comments', locals: {commented_entry: @extract, field: 'translation'}
          = render partial: 'comments/add_comment', locals: {target_id: 'translationComment', field: 'translation', commentable: @extract, comment: Comment.new}

  .row.mb-3
    .col-12
      .card
        .card-body
          .card-text
            .row
              .col-3
                Edition:
                = @extract.edition_position
              .col-3
                Manuscript:
                = @extract.manuscript_position
              .col-3
                Text:
                = @extract.text_position
              .col-3
                - if @extract.unchecked_quote
                  unchecked quote
                - else
                  Quote:
                  = @extract.quote_type
                  = @extract.quote_origin

  .row
    .col-1.text-center
      = user_info_tooltip @extract
    .col-7
      - unchecked_upload_note @extract
      - wrong_tag_count_note @extract
    .col-2
      - unless @extract.checked_upload
        = link_to "#{fa_icon('check')} Check".html_safe, check_upload_extract_path(@extract), class: 'btn btn-resource-action'
    .col-2
      = link_to "#{fa_icon('edit')} Edit Extract".html_safe, edit_extract_path, class: 'btn btn-block btn-resource-action text-right'


  %h3.mt-5.mb-3
    Attestations
  .row
    .col-12
      = link_to "#{fa_icon('plus')} New Attestation".html_safe, new_attestation_path(params: {extract_id: @extract.id}), class: 'btn btn-resource-action'
  .row.mt-3
    .col-12
      .card
        .card-body
          .card-text
            %ul.preview-list
              - @extract.attestations.each do |a|
                %li= render partial: 'attestations/preview', locals: {attestation: a}