config/routes.rb
Rails.application.routes.draw do
  resources :comments do
    collection do
      get :toggle_please_check
    end
  end
  resources :attestations
  resources :users
  resources :extracts do
    member do
      get :check_upload
    end
  end

  get 'text_dashboard', to: 'dashboards#text_module'
  resources :dashboards do
    collection do
      post :upload_and_parse
    end
  end


  root to: 'dashboards#text_module'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :code, presence: true, uniqueness: { case_sensitive: false },format: {with: /(\A[A-ZÄÖÜ][a-zäöüß][A-ZÄÖÜ][a-zäöüß])\z|(\AAdmin\z)/}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url, flash: {success: 'User was successfully created.'}
    else
      flash.now[:error] = "The following errors occurred. Please fix them and try again:\n #{@user.errors.full_messages.join('. ')}."
      render :new
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:code)
  end
end

app/views/users/index.html.haml
%nav{'aria-label': 'breadcrumb', role: 'navigation'}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to 'Text Module Dashboard', text_dashboard_url
    %li.breadcrumb-item.active{'aria-current': 'page'}
      Users

.container
  .row
    .col-12
      %h1.mb-4.border-bottom
        Users

  %table.table
    %thead.thead-light
      %tr
        %th Code
        %th= '#Extracts'
        %th= '#Attestations'
    %tbody
      - @users.order(:code).each do |user|
        %tr
          %td= user.code
          %td= Extract.where(created_by: user).count
          %td= Attestation.where(created_by: user).count

  .row
    .col-12
      = link_to 'New User', new_user_path

app/views/users/new.html.haml
%nav{'aria-label': 'breadcrumb', role: 'navigation'}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to 'Text Module Dashboard', text_dashboard_url
    %li.breadcrumb-item.active{'aria-current': 'page'}
      = link_to 'Users', users_path

.container
  .row.mb-3
    .col-12
      = form_with(model: @user, local: true) do |form|
        .field
          = form.label :code
          = form.text_field :code
        .actions
          = form.submit