config/routes.rb
Rails.application.routes.draw do
  resources :comments do
    collection do
      get :toggle_please_check
    end
  end
  resources :attestations
  resources :users
  resources :extracts do
    member do
      get :check_upload
    end
  end

  get 'text_dashboard', to: 'dashboards#text_module'
  resources :dashboards do
    collection do
      post :upload_and_parse
    end
  end


  root to: 'dashboards#text_module'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def text_module
    # goes to text module
  end

  def upload_and_parse
    uploaded_io = params[:file]

    begin
      inserted_extracts = save_and_parse_file uploaded_io
    rescue StandardError => e
      redirect_to text_dashboard_path, flash: { error: "An error occurred: #{e.message}" }
      return
    end

    redirect_to root_path, flash: { success: "#{inserted_extracts.count} extracts inserted!" }
  end

  private

  def save_and_parse_file(uploaded_io)
    raise Exceptions::InvalidExtractFile, 'No file selected!' if uploaded_io.nil?

    save_path = unique_save_path uploaded_io.original_filename
    File.open(save_path, 'wb') do |file|
      file.write(uploaded_io.read)
    end
    Tools::ExtractParser.new(save_path).read_and_process
  end

  def unique_save_path(filename)
    parts = filename.split('.')
    parts[-2] = "#{parts[-2]}#{Time.now.to_i}"
    parts = parts[0...-1] << parts[-1]
    filename = parts.join('.')
    directory = Rails.root.join('storage', 'extracts')
    FileUtils.mkdir_p(directory) unless File.directory? directory
    Rails.root.join('storage', 'extracts', filename)
  end

end

app/views/dashboards/_unchecked_uploads.html.haml
- User.all.each do |user|
  - extracts = Extract.where(checked_upload: false, created_by_id: user.id).order(:id)
  - if extracts.count > 0
    .card.mb-3
      .card-header
        = "Unchecked Uploads from #{user.code} (#{extracts.count})"
      .card-body
        %ul.preview-list
          - extracts.each do |extract|
            %li
              .row
                .col-12
                  = render partial: 'extracts/preview', locals: {extract: extract}
              .row.mt-2
                .col-12
                  = link_to "#{fa_icon('check')} Check".html_safe, check_upload_extract_path(extract), class: 'btn btn-resource-action'

app/views/dashboards/text_module.html.haml
%nav{'aria-label': 'breadcrumb', role: 'navigation'}
  %ol.breadcrumb
    %li.breadcrumb-item.active{'aria-current': 'page'}
      Text Module Dashboard

.container
  .row
    .col-12
      %h1.mb-4.border-bottom
        Text Module Dashboard
  .row
    .col-8
      .card.h-100
        .card-header
          Upload Extracts
        .card-body
          = form_tag upload_and_parse_dashboards_path, multipart: true do
            = file_field_tag :file, accept: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
            = submit_tag 'Start Upload', class: 'btn btn-primary float-right'
    .col-4
      .card.h-100
        .card-header
          Navigation
        .card-body
          = link_to 'Extracts', extracts_url
          |
          = link_to 'Attestations', attestations_url
          |
          = link_to 'Comments', comments_url
          |
          = link_to 'Users', users_url
  .row.mt-4
    .col-12
      = render 'unchecked_uploads'